import type { Metadata } from "next";
import "./globals.css";
import { Manrope, Plus_Jakarta_Sans, Poppins, Questrial, Lato, Be_Vietnam_Pro,Inter,Geist } from "next/font/google";

const geistSans = Geist({variable: "--font-geist-sans",subsets: ["latin"],});

const manrope = Manrope({subsets: ["latin"],display: "swap", });

const plusJakartaSans = Plus_Jakarta_Sans({variable: "--font-plus-jakarta",subsets: ["latin"],display: "swap",});

const poppins = Poppins({  weight: ['500'], subsets: ["latin"], variable: "--font-poppins", display: "swap" });

const questrial = Questrial({weight:['400'], subsets: ["latin"], variable: "--font-questrial", display: "swap" });

const lato = Lato({ subsets: ["latin"], variable: "--font-lato", display: "swap", weight: ["400", "700","100","300","900"] });

const beVietnam = Be_Vietnam_Pro({weight:["500"], subsets: ["latin"], variable: "--font-bevietnam", display: "swap" });

const inter = Inter({weight:["300"], subsets: ["latin"], variable: "--font-inter", display: "swap" });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${poppins.variable} 
          ${questrial.variable}  
          ${manrope.className} 
          ${plusJakartaSans.variable} 
          ${lato.variable}
          ${beVietnam.variable}
          ${inter.variable}
           antialiased`}

          extension-installed="true"
        
      >
        {children}
      </body>
    </html>
  );
}
